---
title: "Week 5"
author: "Benedetto Lo Cicero"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r knitr_init, cache=FALSE, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```



## Assignment

as answer to the assignment I present here the temperature-pressure dataset plot, the first 6 rows of the mtcars dataset, and again a plot of the mtcars dataset

1. Pressure plot
2. Table
3. Mtcars plot


## Plot pressure

A plot of the built-in pressure dataset

```{r fig.width=6, fig.height=6, fig.align='center'}
library(ggplot2)
library(dplyr)
data(pressure)
ggplot(pressure,aes(x=temperature, y=pressure))+geom_point()

```

## Table

```{r}
library(kableExtra)
data(mtcars)
mtcars %>%  head() %>% kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

## Plot mtcars

A plot of the built-in mtcars dataset

```{r fig.width=6, fig.height=6, fig.align='center'}
library(ggplot2)
library(dplyr)

ggplot(mtcars,aes(x=mpg, y=disp))+geom_point(aes(color=cyl))


```


